name: Lint, format, build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: 'install --network-concurrency 1'
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: check-fmt
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
